services:
  web:
    build: ./web
    environment:
      UNIVERSITY_DEPARTMENT: "國立臺東大學資訊工程學系"
      UNIVERSITY_DEPARTMENT_ABBREVIATION: "NTTU CSIE"
      UNIVERSITY_DEPARTMENT_ABBREVIATION_CN: "東大資工系"
      UNIVERSITY_ADDRESS: "臺東縣臺東市大學路二段369號"
      UNIVERSITY_PHONE: "089-853-000"
      UNIVERSITY_EMAIL: "csie@nttu.edu.tw"
      UNIVERSITY_WEBSITE: "https://www.nttu.edu.tw/"
      BACKEND_URL: "http://api:10000"
      ADMIN: "admin"
      ADMIN_PASSWORD: "admin"
      HOST: "localhost:8080" # need to replace with your host
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - internal

  api:
    build: ./api
    ports:
      - "10000:10000"
    environment:
      MONGO_URL: "mongodb://mongo:27017/"
      HOST: "0.0.0.0"
    depends_on:
      - mongo
    networks:
      - internal

  mongo:
    image: mongo
    ports:
      - ":27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - internal

networks:
  internal:
    driver: bridge